export const mockStatusData = {
  settings: {
    showHeaderSummary: true,
    showNextDue: true,
    showStats: true,
    showFilters: true,
    showCategories: true,
    showProgress: true,
    showLiveStatusPill: true,
    showLiveAge: true,
  },
  statusEntries: [
    {
      id: 'mock-payout-urgent',
      category: 'Auszahlungen & Vergütung',
      title: 'Auszahlungslauf Mai final prüfen',
      status: 'Dringend',
      owner: 'Operator',
      type: 'task',
      priority: 'Hohe Priorität',
      showProgress: false,
      createdAt: '2026-05-18',
      updatedAt: '2026-05-24',
      dueDate: '2026-05-24',
      description:
        'Die letzten Rückmeldungen aus der Prüfung sind eingegangen. Freigabe und Versand der finalen Übersicht stehen noch aus.',
    },
    {
      id: 'mock-tax-documents',
      category: 'Auszahlungen & Vergütung',
      title: 'Steuerunterlagen nachreichen',
      status: 'Offen',
      owner: 'Operator',
      type: 'task',
      priority: 'Mittlere Priorität',
      showProgress: false,
      createdAt: '2026-05-19',
      updatedAt: '2026-05-22',
      dueDate: '2026-05-28',
      description:
        'Zwei Dokumente fehlen noch. Sobald sie vorliegen, kann die interne Prüfung abgeschlossen werden.',
    },
    {
      id: 'mock-bank-details',
      category: 'Auszahlungen & Vergütung',
      title: 'Bankdatenabgleich abgeschlossen',
      status: 'Erledigt',
      owner: 'Operator',
      type: 'info',
      priority: '',
      showProgress: false,
      createdAt: '2026-05-15',
      updatedAt: '2026-05-18',
      dueDate: '2026-05-18',
      description:
        'Alle hinterlegten Bankverbindungen wurden geprüft. Es sind keine weiteren Rückfragen offen.',
    },
    {
      id: 'mock-campaign-copy',
      category: 'Marketing & Sichtbarkeit',
      title: 'Kampagnentexte für Juni abstimmen',
      status: 'Neu',
      owner: 'Techbuddy',
      type: 'task',
      priority: 'Mittlere Priorität',
      showProgress: false,
      createdAt: '2026-05-23',
      updatedAt: '2026-05-23',
      dueDate: '2026-05-30',
      description:
        'Die Textvarianten sind vorbereitet und werden im nächsten Schritt mit den geplanten Motiven abgeglichen.',
    },
    {
      id: 'mock-profile-assets',
      category: 'Marketing & Sichtbarkeit',
      title: 'Profilbilder und Kurzvita aktualisieren',
      status: 'Offen',
      owner: 'Techbuddy',
      type: 'task',
      priority: 'Mittlere Priorität',
      showProgress: false,
      createdAt: '2026-05-17',
      updatedAt: '2026-05-21',
      dueDate: '2026-05-29',
      description:
        'Neue Bilddateien sind teilweise eingegangen. Die offenen Profile werden gesammelt aktualisiert.',
    },
    {
      id: 'mock-landing-page',
      category: 'Marketing & Sichtbarkeit',
      title: 'Landingpage-Abschnitt freigeben',
      status: 'Dringend',
      owner: 'Techbuddy',
      type: 'task',
      priority: 'Hohe Priorität',
      showProgress: false,
      createdAt: '2026-05-20',
      updatedAt: '2026-05-24',
      dueDate: '2026-05-25',
      description:
        'Der neue Abschnitt ist eingebaut. Vor Veröffentlichung fehlt noch die finale inhaltliche Freigabe.',
    },
    {
      id: 'mock-roundtable',
      category: 'Termine & Koordination',
      title: 'Expertenrunde Terminblock bestätigen',
      status: 'Offen',
      owner: 'Operator',
      type: 'task',
      priority: 'Hohe Priorität',
      showProgress: false,
      createdAt: '2026-05-18',
      updatedAt: '2026-05-22',
      dueDate: '2026-05-26',
      description:
        'Drei Zeitfenster stehen zur Auswahl. Die Rückmeldungen werden gesammelt und anschließend final bestätigt.',
    },
    {
      id: 'mock-onboarding-call',
      category: 'Termine & Koordination',
      title: 'Onboarding-Call vorbereiten',
      status: 'Neu',
      owner: 'Operator',
      type: 'task',
      priority: 'Mittlere Priorität',
      showProgress: false,
      createdAt: '2026-05-24',
      updatedAt: '2026-05-24',
      dueDate: '2026-06-01',
      description:
        'Agenda und Teilnehmerliste werden vorbereitet. Die Einladung folgt nach Bestätigung des Zeitfensters.',
    },
    {
      id: 'mock-calendar-cleanup',
      category: 'Termine & Koordination',
      title: 'Kalendereinträge bereinigt',
      status: 'Erledigt',
      owner: 'Operator',
      type: 'info',
      priority: '',
      showProgress: false,
      createdAt: '2026-05-16',
      updatedAt: '2026-05-20',
      dueDate: '2026-05-20',
      description:
        'Doppelte Einladungen wurden entfernt. Die aktuelle Terminübersicht ist wieder konsistent.',
    },
    {
      id: 'mock-contract-question',
      category: 'Weitere Themen',
      title: 'Rückfrage zur Vertragsanlage klären',
      status: 'Dringend',
      owner: 'Operator',
      type: 'task',
      priority: 'Hohe Priorität',
      showProgress: false,
      createdAt: '2026-05-21',
      updatedAt: '2026-05-24',
      dueDate: '2026-05-24',
      description:
        'Eine Formulierung in der Anlage ist noch offen. Nach Klärung kann das Dokument finalisiert werden.',
    },
    {
      id: 'mock-tool-access',
      category: 'Website & Updates',
      title: 'Tool-Zugänge prüfen',
      status: 'Offen',
      owner: 'Techbuddy',
      type: 'task',
      priority: 'Mittlere Priorität',
      showProgress: false,
      createdAt: '2026-05-19',
      updatedAt: '2026-05-21',
      dueDate: '2026-05-27',
      description:
        'Einige Zugänge wurden bereits bestätigt. Die restlichen Berechtigungen werden gesammelt geprüft.',
    },
    {
      id: 'mock-faq-update',
      category: 'Website & Updates',
      title: 'FAQ-Erweiterung veröffentlicht',
      status: 'Erledigt',
      owner: 'Techbuddy',
      type: 'info',
      priority: '',
      showProgress: false,
      createdAt: '2026-05-14',
      updatedAt: '2026-05-19',
      dueDate: '2026-05-19',
      description:
        'Die neuen Antworten sind online. Weitere Ergänzungen werden bei Bedarf im nächsten Update gesammelt.',
    },
  ],
}
